spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: gilded-rose

logging:
    level:
        org.springframework: ERROR
        com.gildedrose: DEBUG